---
    chain:    
        -
            name: "checklog"
            ref: fenego.logchecker
            parameters:
                agg_key: '{{agg_key}}'
                alert_id: '{{alert_id}}'
                alert_metric: '{{alert_metric}}'
                alert_query: '{{alert_query}}'
                alert_transition: '{{alert_transition}}'
                alert_status: '{{alert_status}}'
                title: '{{title}}'
                last_updated: '{{last_updated}}'
                date: '{{date}}'
                event_type: '{{event_type}}'
                body: '{{body}}'
                user: '{{user}}'
                link: '{{link}}'
                priority: '{{priority}}'   
                tags: '{{tags}}'
                host: '{{host}}'     
                snapshot: '{{snapshot}}'
                stackstormpath: '{{stackstormpath}}'
                frequency: '{{frequency}}'
                period: '{{period}}'
                company: '{{company}}'
                email: '{{email}}'
            on-success: "executecmd" 
            on-failure: "send mail"  
        -
            name: "send mail"
            ref: fenego.Mail
            parameters:
                message: "{{checklog.stdout}}" 
            on-success: "Send to Slack" 
            on-failure: "Send to Slack"
        -
            name: "executecmd"
            ref: fenego.ExecuteCommand
            parameters:
                stackstormpath: '{{stackstormpath}}'
                host: '{{host}}'
                cmd: '{{cmd}}'
                company: '{{company}}'
            on-failure: "cmd to Slack"
            on-success: "StatusCheck"
        -
            name: "StatusCheck"
            ref: fenego.StatusCheck
            parameters:
                logfile: '{{logfile}}' 
                servicename: '{{servicename}}'
                attempts: '{{attempts}}'
        -
            name: "Send to Slack"
            ref: fenego.Slack
            parameters:
                message: '{{checklog.stdout}}'
        -
            name: "cmd to Slack"
            ref: fenego.Slack
            parameters:
                message: '{{executecmd.stdout}}'
                     
    default: "checklog"
