---
# Action definition metadata
name: "Service"
description: "Simple Action Chain workflow"

# `runner_type` has value `action-chain` to identify that action is an ActionChain.
runner_type: "action-chain"

# `entry_point` path to the ActionChain definition file, relative to the pack's action directory.
entry_point: "chains/service.yaml"

enabled: true
parameters:
    agg_key: 
        type: "string"
        required: true
    alert_id: 
        type: "string"
        required: true
    alert_metric:
        type: "string"
        required: true 
    alert_query:
        type: "string"
        required: true
    alert_transition:
        type: "string"
        required: true
    alert_status:
        type: "string"
        required: true
    title:
        type: "string"
        required: true
    last_updated:
        type: "string"
        required: true
    date:
        type: "string"
        required: true
    event_type:
        type: "string"
        required: true
    body:
        type: "string"
        required: true
    user: 
        type: "string"
        required: true
    link: 
        type: "string"
        required: true
    priority:
        type: "string"
        required: true
    tags:
        type: "string"
        required: true
    host:
        type: "string"
        required: true
    snapshot:
        type: "string"
        required: true
    stackstormpath:
        type: "string"
        required: true
    frequency:
        type: "integer"
        required: true
    period:
        type: "integer"
        required: true
    cmd:
        type: "string"
        required: true
    company:
        type: "string"
        required: true
    email:
        type: "string"
        required: false
    logfile:
        type: "string"
        required: true
    servicename:
        type: "string"
        required: true
    attempts:
        type: "integer"
        required: false

